//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavViewerTests {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavViewerTests.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OBJECT-PROPERTIES
        ///  {
        ///    Date=15/02/20;
        ///    Time=21:54:29;
        ///    Modified=Yes;
        ///    Version List=NAVW19.00;
        ///  }.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PROPERTIES
        ///  {
        ///    DataCaptionFields=No.,Sell-to Customer Name;
        ///    OnInsert=BEGIN
        ///               InitInsert;
        ///               InsertMode := TRUE;
        ///
        ///               IF GetFilterCustNo &lt;&gt; &apos;&apos; THEN
        ///                 VALIDATE(&quot;Sell-to Customer No.&quot;,GetFilterCustNo);
        ///
        ///               IF GetFilterContNo &lt;&gt; &apos;&apos; THEN
        ///                 VALIDATE(&quot;Sell-to Contact No.&quot;,GetFilterContNo);
        ///
        ///               &quot;Doc. No. Occurrence&quot; := ArchiveManagement.GetNextOccurrenceNo(DATABASE::&quot;Sales Header&quot;,&quot;Document Type&quot;,&quot;No.&quot;);
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à { 3   ;   ;No.                 ;Code20        ;OnValidate=BEGIN
        ///                                                                IF &quot;No.&quot; &lt;&gt; xRec.&quot;No.&quot; THEN BEGIN
        ///                                                                  SalesSetup.GET;
        ///                                                                  NoSeriesMgt.TestManual(GetNoSeriesCode);
        ///                                                                  &quot;No. Series&quot; := &apos;&apos;;
        ///                                                                END;
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FIELDS
        ///  {
        ///    { 1   ;   ;Document Type       ;Option        ;CaptionML=[ENU=Document Type;
        ///                                                              FRA=Type document];
        ///                                                   OptionCaptionML=[ENU=Quote,Order,Invoice,Credit Memo,Blanket Order,Return Order;
        ///                                                                    FRA=Devis,Commande,Facture,Avoir,Commande ouverte,Retour];
        ///                                                   OptionString=Quote,Ord [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VAR
        ///      Text000@1000 : TextConst &apos;ENU=Do you want to print shipment %1?;FRA=Souhaitez-vous imprimer le B.L. %1?&apos;;
        ///      Text001@1001 : TextConst &apos;ENU=Do you want to print invoice %1?;FRA=Souhaitez-vous imprimer la facture %1?&apos;;
        ///      Text002@1002 : TextConst &apos;ENU=Do you want to print credit memo %1?;FRA=Souhaitez-vous imprimer l&apos;&apos;avoir %1?&apos;;
        ///      Text003@1003 : TextConst &apos;ENU=You cannot rename a %1.;FRA=Vous ne pouvez pas renommer l&apos;&apos;enregistrement %1.&apos;;
        ///      Text004@1004 : TextConst &apos;ENU=Do you wa [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CODE
        ///  {
        ///    VAR
        ///      Bin@1000 : Record 7354;
        ///      Postcode@1001 : Record 225;
        ///      WhseSetup@1002 : Record 5769;
        ///      InvtSetup@1003 : Record 313;
        ///      Location@1004 : Record 14;
        ///      Text000@1005 : TextConst &apos;ENU=You cannot delete the %1 %2, because they contain items.;FRA=Vous ne pouvez pas supprimer l&apos;&apos;enregistrement %1 %2, car il contient des articles.&apos;;
        ///      Text001@1006 : TextConst &apos;ENU=You cannot delete the %1 %2, because one or more Warehouse Activity Lines exist for this %1.;FRA=Vo [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FIELDS
        ///  {
        ///    { 1   ;   ;Code                ;Code10        ;CaptionML=[ENU=Code;
        ///                                                              FRA=Code];
        ///                                                   NotBlank=Yes }
        ///    { 2   ;   ;Name                ;Text50        ;CaptionML=[ENU=Name;
        ///                                                              FRA=Nom] }
        ///    { 130 ;   ;Default Bin Code    ;Code20        ;TableRelation=Bin.Code WHERE (Location Code=FIELD(Code));
        ///                             [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OBJECT Table 8 Language
        ///{
        ///  OBJECT-PROPERTIES
        ///  {
        ///    Date=15/09/15;
        ///    Time=12:00:00;
        ///    Version List=NAVW19.00;
        ///  }
        ///  PROPERTIES
        ///  {
        ///    CaptionML=[ENU=Language;
        ///               FRA=Langue];
        ///    LookupPageID=Page9;
        ///  }
        ///  FIELDS
        ///  {
        ///    { 1   ;   ;Code                ;Code10        ;CaptionML=[ENU=Code;
        ///                                                              FRA=Code];
        ///                                                   NotBlank=Yes }
        ///    { 2   ;   ;Name                ;Text50      [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
    }
}
